controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      joint1:
        p: 4000.0
        d: 10.0
        i: 250.0
        i_clamp: 15.0
      joint2:
        p: 10000.0
        d: 25.0
        i: 600.0
        i_clamp: 45.0
      joint3:
        p: 8000.0
        d: 20.0
        i: 450.0
        i_clamp: 30.0
      joint4:
        p: 6000.0
        d: 15.0
        i: 300.0
        i_clamp: 30.0
      joint5:
        p: 3000.0
        d: 5.0
        i: 175.0
        i_clamp: 7.0
      joint6:
        p: 2500.0
        d: 3.0
        i: 150.0
        i_clamp: 6.0
      joint7:
        p: 2000.0
        d: 2.0
        i: 10.0
        i_clamp: 5.0